[project]
name = "tom-transients-fyi"
description = "A TOM Toolkit data service for transients.fyi: a view's objects and their light curves, with limits, as targets"
authors = [
    {name = "Justin Greene", email = "justin.greene5@gmail.com"}
]
license = {text = "GPL-3.0-only"}
readme = "README.md"
dynamic = ["version"]
requires-python = ">=3.10,<3.14"
dependencies = [
    "tomtoolkit (>=3.0.0,<4.0.0)",
    "requests (>=2.28,<3)",
]

[project.urls]
Homepage = "https://transients.fyi/data"

[tool.poetry]
version = "0.0.0" # version supplied by poetry-dynamic-versioning

[tool.poetry.group.test.dependencies]
factory_boy = ">3.2.1,<3.4"

[tool.poetry.group.coverage.dependencies]
coverage = ">=6,<8" # coveralls needs ~6 even though 7.3.2 is latest
coveralls = ">=3,<5"

[tool.poetry.group.lint.dependencies]
flake8 = ">=6.0,<7.4"

[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version = ">=1.0.0,<2.0.0", extras = ["plugin"] }

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"
# the default pattern regex makes the 'v' mandatory
# this pattern modifies the default regex in order to make the 'v' optional
# ('v' becomes '[v]?' meaning a single v, [v], and ? means optional)
pattern = "(?x)^[v]?((?P<epoch>\\d+)!)?(?P<base>\\d+(\\.\\d+)*)([-._]?((?P<stage>[a-zA-Z]+)[-._]?(?P<revision>\\d+)?))?(\\+(?P<tagged_metadata>.+))?$"

# substitute version not only in pyproject.toml (which the config block above does)
# but also the __version__.py file (using the default value of the files property).
[tool.poetry-dynamic-versioning.substitution]

[build-system]
requires = ["poetry-core >=2.0.0, <3.0.0", "poetry-dynamic-versioning >=0.22.0"]
build-backend = "poetry_dynamic_versioning.backend"
